-- A EXECUTER AVEC USER ROOT
DROP DATABASE IF EXISTS `opencr_db_prj03`;
DROP USER IF EXISTS `opencr_user`@`%`;
CREATE DATABASE IF NOT EXISTS `opencr_db_prj03` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `opencr_user`@`%` IDENTIFIED BY 'opencr_pw1!';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `opencr_db_prj03`.* TO `opencr_user`@`%`;